### ISSUE TITLE
Add ability to enable custom style for tooltip-cards 

### ISSUE THREAD

**Issue by Criticalcarpet** [Criticalcarpet/Hyperlinks#4]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
Add ability to enable custom style for tooltip-cards 

**Describe alternatives you've considered**
NO

**Additional context**
NO

**Comment by Manik2375** [comment]
I believe it's better to add support for classes, rather than something like `cssText` because it can creates problems..
